### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AlexHimself** [MicrosoftDocs/DynamicsAX2012-technet#236]
The URL is broken as far as I can tell. Ultimately it redirects to:

https://mbs.microsoft.com/DownLoads/public/customer/Change%20management%20and%20TFS%20integration%20for%20multi%20developer%20projects_AX2012.docx

Which doesn't seem to work for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6ac4b8-d16d-5faa-c47f-a6ff7d5ac79f
* Version Independent ID: c12dd48b-58b2-c392-2b61-313eda1c8561
* Content: [Change management and TFS integration for multi-developer projects  (white paper)](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/change-management-and-tfs-integration-for-multi-developer-projects-white-paper)
* Content Source: [dynamicsax2012-technet/change-management-and-tfs-integration-for-multi-developer-projects-white-paper.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/change-management-and-tfs-integration-for-multi-developer-projects-white-paper.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by tonyafehr** [comment]
The link should work now.

**Comment by AlexHimself** [comment]
> The link should work now.

I still can't get this one to work. CustomerSource has a `Server Error in '/' Application.` if I login and there is no PartnerSource link provided.

This file is way too difficult to download and it still isn't available wherever I try.
